version: '3'

silent: true

vars:
  SERVICE_NAME: TicketServicio
  SERVICE_TEST: TicketServicioTest
  SERVICE_REMOTE: TicketServicioRemote
  BINARY: R2k_TicketServicio_Local.exe
  BINARY_REMOTE: R2k_TicketServicio_Remote.exe
  BUILD_DIR: ./bin
  MODULE: github.com/adcondev/ticket-daemon/internal/daemon

# Default task - show help
tasks:
  default:
    desc: "Show available commands"
    silent: true
    cmds:
      - |
        echo  
        echo โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
        echo   TICKET DAEMON - Service Manager
        echo โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
        echo  
        echo   QUICK START:
        echo     task build        Build the service - test mode
        echo     task run          Build and run locally
        echo  
        echo   SERVICE MANAGEMENT  Run as Administrator:
        echo     task install      Install as Windows Service
        echo     task uninstall    Remove Windows Service
        echo     task start        Start the service
        echo     task stop         Stop the service
        echo     task restart      Restart the service
        echo     task status       Check service status
        echo  
        echo   DEBUGGING:
        echo     task logs         View logs in real-time
        echo     task health       Check health endpoint
        echo     task open         Open test client in browser
        echo  
        echo   CLEANUP:
        echo     task clean        Remove build artifacts
        echo  

  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # BUILD
  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  build:
    desc: "Build service for testing (localhost: 8766)"
    cmds:
      - powershell -Command "if (!(Test-Path '{{.BUILD_DIR}}')) { New-Item -ItemType Directory -Path '{{.BUILD_DIR}}' -Force | Out-Null }"
      - go build -ldflags "-s -w -H=windowsgui -X {{.MODULE}}.BuildEnvironment=test -X {{.MODULE}}.BuildDate={{.DATE}} -X {{.MODULE}}.BuildTime={{.TIME}}" -o {{.BUILD_DIR}}/{{.BINARY}} ./cmd/TicketServicio
      - powershell -Command "Write-Host 'โ Built {{.BUILD_DIR}}/{{.BINARY}}'"
    vars:
      DATE:
        sh: powershell -Command "Get-Date -Format 'yyyy-MM-dd'"
      TIME:
        sh: powershell -Command "Get-Date -Format 'HH:mm:ss'"

  build-prod:
    desc: "Build service for production (0.0.0.0:8766)"
    cmds:
      - powershell -Command "if (!(Test-Path '{{.BUILD_DIR}}')) { New-Item -ItemType Directory -Path '{{.BUILD_DIR}}' -Force | Out-Null }"
      - go build -ldflags "-s -w -X {{.MODULE}}.BuildEnvironment=prod -X {{.MODULE}}.BuildDate={{.DATE}} -X {{.MODULE}}.BuildTime={{.TIME}}" -o {{.BUILD_DIR}}/{{.BINARY_REMOTE}} ./cmd/TicketServicio
      - powershell -Command "Write-Host 'โ Built {{.BUILD_DIR}}/{{.BINARY_REMOTE}} (PRODUCTION)'"
    vars:
      DATE:
        sh: powershell -Command "Get-Date -Format 'yyyy-MM-dd'"
      TIME:
        sh: powershell -Command "Get-Date -Format 'HH:mm:ss'"

  build-console:
    desc: "Build standalone console executable (double-click to run)"
    cmds:
      - powershell -Command "if (!(Test-Path '{{.BUILD_DIR}}')) { New-Item -ItemType Directory -Path '{{.BUILD_DIR}}' -Force | Out-Null }"
      - go build -ldflags "-s -w -X {{.MODULE}}.BuildEnvironment=test -X {{.MODULE}}.BuildDate={{.DATE}} -X {{.MODULE}}.BuildTime={{.TIME}}" -o {{.BUILD_DIR}}/TicketDaemon_Console.exe ./cmd/TicketServicio
      - powershell -Command "Write-Host 'โ Built {{.BUILD_DIR}}/TicketDaemon_Console.exe (Console Mode)'"
      - powershell -Command "Write-Host '   Double-click to run, Ctrl+C to stop'"
    vars:
      DATE:
        sh: powershell -Command "Get-Date -Format 'yyyy-MM-dd'"
      TIME:
        sh: powershell -Command "Get-Date -Format 'HH:mm:ss'"

  run:
    desc: "Build and run locally (console mode)"
    deps: [ build ]
    cmds:
      - echo ๐ Starting Ticket Daemon...
      - echo    WebSocket:ws://localhost:8766/ws
      - echo    Test client:http://localhost:8766
      - echo    Press Ctrl+C to stop
      - echo
      - '{{.BUILD_DIR}}/{{.BINARY}}'

  run-console:
    desc: "Build and run in console mode (visible window)"
    deps: [ build-console ]
    cmds:
      - echo
      - echo โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
      - echo   TICKET DAEMON - Console Mode
      - echo   WebSocket:ws://localhost:8766/ws
      - echo   Dashboard:http://localhost:8766
      - echo   Press Ctrl+C to stop
      - echo โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
      - echo
      - '{{.BUILD_DIR}}/TicketDaemon_Console.exe'

  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # SERVICE MANAGEMENT (Requires Administrator)
  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  install:
    desc: "Install as Windows Service (requires Admin)"
    deps: [ build ]
    cmds:
      - cmd: sc stop {{.SERVICE_TEST}} 2>nul
        ignore_error: true
      - cmd: sc delete {{.SERVICE_TEST}} 2>nul
        ignore_error: true
      - sc create {{.SERVICE_TEST}} binPath= "{{.ABS_PATH}}\{{.BUILD_DIR}}\{{.BINARY}}" start= auto DisplayName= "Ticket Daemon (Test)"
      - sc description {{.SERVICE_TEST}} "Servicio de impresion de tickets POS via WebSocket"
      - sc start {{.SERVICE_TEST}}
      - echo
      - echo โ Service installed and started!
      - echo Test client:http://localhost:8766
    vars:
      ABS_PATH:
        sh: powershell -Command "(Get-Location).Path"

  install:remote:
    desc: "Install as Windows Service (Remote) (requires Admin)"
    deps: [ build-prod ]
    cmds:
      - cmd: sc stop {{.SERVICE_REMOTE}} 2>nul
        ignore_error: true
      - cmd: sc delete {{.SERVICE_REMOTE}} 2>nul
        ignore_error: true
      - sc create {{.SERVICE_REMOTE}} binPath= "{{.ABS_PATH}}\{{.BUILD_DIR}}\{{.BINARY_REMOTE}}" start= auto DisplayName= "Servicio de Tickets POS (Remoto)"
      - sc description {{.SERVICE_REMOTE}} "Servicio de impresiรณn de tickets POS via WebSocket"
      - sc start {{.SERVICE_REMOTE}}
      - echo
      - echo โ Service installed and started!
      - echo Production service listening on all interfaces
    vars:
      ABS_PATH:
        sh: powershell -Command "(Get-Location).Path"

  uninstall:
    desc: "Remove Windows Service (requires Admin)"
    cmds:
      - cmd: sc stop {{.SERVICE_TEST}} 2>nul
        ignore_error: true
      - sc delete {{.SERVICE_TEST}}
      - echo โ Service removed

  uninstall:remote:
    desc: "Remove Remote Windows Service (requires Admin)"
    cmds:
      - cmd: sc stop {{.SERVICE_REMOTE}} 2>nul
        ignore_error: true
      - sc delete {{.SERVICE_REMOTE}}
      - echo โ Remote service removed

  start:
    desc: "Start the service"
    cmds:
      - sc start {{.SERVICE_TEST}}
      - echo โ Service started

  stop:
    desc: "Stop the service"
    cmds:
      - sc stop {{.SERVICE_TEST}}
      - echo โ Service stopped

  restart:
    desc: "Restart the service"
    cmds:
      - cmd: sc stop {{.SERVICE_TEST}} 2>nul
        ignore_error: true
      - powershell -Command "Start-Sleep -Seconds 2"
      - sc start {{.SERVICE_TEST}}
      - echo โ Service restarted

  status:
    desc: "Check service status"
    cmds:
      - sc query {{.SERVICE_TEST}}

  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # DEBUGGING
  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  logs:
    desc: "View last 100 log lines"
    cmds:
      - powershell -Command "Get-Content 'C:\ProgramData\{{.SERVICE_TEST}}\{{.SERVICE_TEST}}.log' -Tail 100"

  health:
    desc: "Check health endpoint"
    cmds:
      - powershell -Command "(Invoke-WebRequest -Uri 'http://localhost:8766/health' -UseBasicParsing).Content"

  open:
    desc: "Open test client in browser"
    cmds:
      - start http://localhost:8766

  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # CLEANUP
  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  clean:
    desc: "Remove build artifacts"
    cmds:
      - cmd: if exist {{.BUILD_DIR}} rmdir /s /q {{.BUILD_DIR}}
        platforms: [ windows ]
      - echo โ Cleaned